"""Audit-ready PDF report (ReportLab). Every figure is read from the stored analysis; nothing is authored here."""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import KeepTogether, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from ..scoring import FORMULA

BAND = {"critical": "#b42318", "high": "#d9480f", "medium": "#b7791f", "low": "#2b6cb0", "info": "#5b6470"}
PROV_NOTE = {
    "synthetic": "SYNTHETIC capture generated by the project's simulator. Findings demonstrate the analyzer; they are NOT a real-world incident.",
    "real-public": "Real third-party capture (Wireshark public samples).",
    "user-upload": "User-supplied capture. Provenance unverified.",
}


def _p(text: Any, style: ParagraphStyle) -> Paragraph:
    return Paragraph(escape(str(text)), style)


def build_pdf(analysis: dict[str, Any], tunnels: list[dict[str, Any]]) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm,
                            bottomMargin=16 * mm, title=f"IPsec VPN assessment - {analysis['filename']}")
    ss = getSampleStyleSheet()
    h1, h2, h3 = ss["Title"], ss["Heading2"], ss["Heading3"]
    body = ParagraphStyle("b", parent=ss["BodyText"], fontSize=9, leading=12)
    small = ParagraphStyle("s", parent=body, fontSize=7.5, leading=10, textColor=colors.HexColor("#444444"))
    mono = ParagraphStyle("m", parent=small, fontName="Courier")
    sm = analysis["summary"]
    out: list[Any] = [
        _p("IPsec VPN Security Assessment", h1),
        _p(f"Capture: {analysis['filename']}   |   Generated {datetime.now():%Y-%m-%d %H:%M}   |   Policy: {sm['policy']}", body),
        Spacer(1, 4),
        Table([[_p("Data provenance", body), _p(PROV_NOTE.get(analysis["provenance"], analysis["provenance"]), body)]],
              colWidths=[35 * mm, 139 * mm],
              style=TableStyle([("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#b7791f")),
                                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fffaf0"))])),
        Spacer(1, 6),
        _p("Summary", h2),
        _p(f"{sm['packets']} packets analysed in {analysis['seconds']} s: {sm['ike_messages']} IKE messages, "
           f"{sm['esp_packets']} ESP packets, {sm['tunnel_count']} tunnel(s). Decryption keys supplied for "
           f"{sm['decrypted_tunnels']} tunnel(s). Risk bands: " + ", ".join(f"{k} {v}" for k, v in sm["bands"].items()) + ".", body),
        Spacer(1, 4),
    ]
    rows = [["Tunnel", "Peers", "Mode", "IKE suite", "Risk", "Band"]]
    for t in tunnels:
        tu = t["tunnel"]
        rows.append([tu["id"][-10:], f"{tu['initiator']} → {tu['responder']}", tu["exchange_mode"],
                     (tu["chosen"] or {}).get("label", "n/a"), t["risk"]["score"], t["risk"]["band"]])
    tbl = Table([[_p(c, small) for c in r] for r in rows], colWidths=[22 * mm, 42 * mm, 24 * mm, 54 * mm, 13 * mm, 19 * mm], repeatRows=1)
    tbl.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8ecf1")), ("GRID", (0, 0), (-1, -1), 0.25, colors.grey)]))
    out += [tbl, Spacer(1, 6), _p("Risk formula", h3), _p(FORMULA, small), _p("Severity weights and bands come from the policy pack.", small)]

    for t in tunnels:
        tu, risk = t["tunnel"], t["risk"]
        blk: list[Any] = [PageBreak(), _p(f"Tunnel {tu['id']}", h2),
                          _p(f"{tu['initiator']} → {tu['responder']} · {tu['exchange_mode']} · status {tu['status']}"
                             f"{' (' + tu['failure'] + ')' if tu['failure'] else ''} · risk {risk['score']} ({risk['band']})", body)]
        blk.append(_p(f"Rules component R = {risk['rules_component']}, anomaly component A = {risk['anomaly_component']}"
                      f" (anomaly score {risk['anomaly_score']})", small))
        viol = [f for f in t["findings"] if f["category"] == "violation"]
        cov = [f for f in t["findings"] if f["category"] == "coverage"]
        blk.append(_p("Findings", h3))
        if not viol:
            blk.append(_p("No policy violations detected.", body))
        for f in viol:
            mitre = ", ".join(f"{m['id']} {m['name']}" for m in f["mitre"]) or "none mapped"
            rem = f["remediation"]
            blk.append(KeepTogether([
                _p(f"[{f['severity'].upper()}] {f['rule_id']} — {f['title']}", ParagraphStyle("f", parent=body, textColor=colors.HexColor(BAND[f["severity"]]), fontName="Helvetica-Bold")),
                _p(f["description"], body),
                _p("Evidence: " + "; ".join(f"{k}={v}" for k, v in f["evidence"].items() if k != "all_offenders")[:600], mono),
                _p("References: " + ", ".join(f["refs"]) + f"   |   MITRE ATT&CK: {mitre}", small),
                _p(f"Remediation — {rem['title']}: " + " ".join(f"({i + 1}) {s}" for i, s in enumerate(rem["steps"])), body),
                Spacer(1, 4)]))
        an = t.get("anomaly")
        if an:
            blk.append(_p("Behavioural anomaly model", h3))
            ex = an["explanation"]
            blk.append(_p(f"Score {an['score']} ({'ANOMALOUS' if an['is_anomalous'] else 'within baseline'}); dominant group: {an['dominant_group']}. "
                          f"Method: {ex['method']}.", body))
            for f in ex.get("top_features", []):
                blk.append(_p(f"{f['label']}: value {f['value']} (benign median {f['baseline_median']}) → SHAP {f['shap']:+} ({f['direction']})", small))
        if cov:
            blk.append(_p("Not assessable from this capture", h3))
            for f in cov:
                blk.append(_p(f"{f['title']}: {f['description']}", small))
        out += blk
    doc.build(out)
    return buf.getvalue()
