import { ReactNode } from "react";

export const PROV_LABEL: Record<string, string> = {
  synthetic: "synthetic (simulated)",
  "real-lab": "real · strongSwan lab",
  "real-public": "real · public sample",
  "user-upload": "user upload",
};

export function Sev({ level }: { level: string }) {
  return <span className={`badge ${level}`}>{level}</span>;
}

export function Prov({ p }: { p: string }) {
  return <span className={`badge prov-${p}`}>{PROV_LABEL[p] ?? p}</span>;
}

export function Meter({ score, band }: { score: number; band: string }) {
  return (
    <div className={`meter ${band}`} role="meter" aria-valuenow={score} aria-valuemin={0} aria-valuemax={100} aria-label={`risk ${score}`}>
      <i style={{ width: `${Math.max(2, Math.min(100, score))}%` }} />
    </div>
  );
}

export function Loading({ what = "Loading" }: { what?: string }) {
  return (
    <div className="empty" role="status">
      <span className="spinner" /> {what}…
    </div>
  );
}

export function ErrorBox({ error, retry }: { error: string; retry?: () => void }) {
  return (
    <div className="banner err" role="alert">
      <b>Something went wrong.</b> {error} {retry && <button onClick={retry}>Retry</button>}
    </div>
  );
}

export function Empty({ children }: { children: ReactNode }) {
  return <div className="empty">{children}</div>;
}

export function ProvBanner({ p, compact = false }: { p: string; compact?: boolean }) {
  const cls = compact ? "banner compact" : "banner";
  if (p === "synthetic")
    return (
      <div className={cls}>
        <b>Simulated capture.</b> This capture was generated by the project's traffic simulator (see README → Data provenance). Findings
        demonstrate the analyzer working on known configurations; they are <b>not</b> a captured real-world incident.
      </div>
    );
  const real = p === "real-lab"
    ? <><b>Real traffic, lab scenario.</b> Genuine IKE/ESP exchanged between two strongSwan daemons in Docker. Weak or downgrade
        configurations are deliberate lab setups, not real-world incidents.</>
    : p === "real-public" ? <><b>Real capture.</b> Public third-party sample from the Wireshark test suite.</> : null;
  if (real) return <div className={cls} style={{ borderColor: "var(--ok)", background: "var(--ok-bg)" }}>{real}</div>;
  return null;
}
